config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  
  get "users/new"
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  get    "/login", to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :categories
    resources :products
    resources :orders
    resources :suggests
    resources :charts
    resources :csv, only: :create
  end
  resources :users
  resources :products, only: [:index, :show]
  resources :carts
  resources :orders
  resources :rates
  resources :suggests  
  resources :comments
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController
 # before_action :total_price, only: [:create, :index]
  
  def index
    @carts = Cart.all
    @cartitems = CartItem.cartitems_product
  end

  def show
    @cartitems = CartItem.cartitems params[:id]
  end

  def create
    @cart = Cart.find_by id: params[:id]
    if params[:key].to_i==0
    @cart.update isStatic: true
    elsif params[:key].to_i==1
    @cart.update isStatic: false
    end
    redirect_to admin_orders_path
  end

  def destroy
    @Cartitems = CartItem.where cart_id: params[:id]
    @cart = Cart.find_by id: params[:id]
    @Cartitems.destroy_all
    @cart.destroy
    redirect_to admin_orders_path
  end

  #private

  #def total_price
  #  @cartitems = CartItem.cartitems params[:id]
  #  @sum = 0;
  #  @cartitems.each do |cartitem|
  #    @sum += cartitem.price * cartitem.count
  #   end
  #end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :create_cart, only: [:create, :index]
  
  def index
    @cartitems = CartItem.showcartitems Cart.find_by(user_id: current_user.id)
  end

  def destroy
    @cartitem = CartItem.find_by id: params[:id]
    @cartitem.destroy
    redirect_to orders_path
  end

  def create
    @cart.update isStatic: false, totalprice: params[:total_price]
    redirect_to orders_path
  end

  private

  def create_cart
    if Cart.find_by(user_id: current_user.id).present?
      @cart = Cart.find_by(user_id: current_user.id)
    else
      @cart = Cart.create! user_id: current_user.id
    end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<% provide :title,t(".show_category") %>
<div class="row">
  <aside class="col-md-2">
  </aside>
    <div class="col-md-10">
      <% if @carts.any? %>
        <ol class="orders">
          <table class="table table-striped">
            <tr>
              <th> User </th>
               <button type="button" class="btn btn-default" id = "btn_delete" value = "Default" >Default</button>
            </tr>
          <% @carts.each do |cart| %>
            <tr> 
              <td><%= link_to cart.user.name, admin_order_path(cart) %></td>
              <td><%= cart.totalprice %></td>
              <% if cart.isStatic? %>
              <th><%= link_to t(".reject"), admin_orders_path(id: cart.id, key: 1), method: :post, class: "btn btn-danger" %></th>
              <% else %>
              <th><%= link_to t(".accept"), admin_orders_path(id: cart.id, key: 0), method: :post, class: "btn btn-success" %></th>
              <% end %>
            </tr>
          <% end %>
          </table>
        </ol>
      <% end %>
    </div>
</div>

app/views/admin/orders/show.html.erb
<% provide :title, t(".all_orders") %>
<h1><%= t ".all_orders" %></h1>
<% @sum = 0 %>
<table class="table table-inverse">
	 <thead>
	 <tr>
	  	<th>Product</th>
		<th>count of each product</th>
		<th>Price of each product</th>
	  </tr>
	   </thead>
  <% @cartitems.each do |item| %>
    <tbody>
	  <tr>
	  	<th><%= item.product.productname %></th>
		<th><%= item.count %></th>
		<th><%= item.price %></th>
		<% @sum += item.count * item.price %>
	  </tr>
	<tbody>
  <% end %>
  <th><%= @sum %></th>
  <th><%= @sum %></th>
   <tr>
   <th><%= link_to t(".back"), admin_orders_path, class: "btn btn-info" %></th>
   </tr>
</table>