config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  
  get "users/new"
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  get    "/login", to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :categories
    resources :products
    resources :orders
    resources :suggests
    resources :charts
    resources :csv, only: :create
  end
  resources :users
  resources :products, only: [:index, :show]
  resources :carts
  resources :orders
  resources :rates
  resources :suggests  
  resources :comments
end

app/models/application_record.rb
require 'csv'
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  
  has_many :cart_items, dependent: :destroy
  

  def group_by_criteria
    created_at.to_date.to_s(:db)
  end
  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product

  scope :cartitems, -> id do
  select("cart_items.*, sum(count) AS Scount, sum(price) AS Sprice").
      where("cart_id = ?", id).
      group("product_id")
  end

  scope :showcartitems, -> id do
  select("cart_items.*").
      where("cart_id = ?", id)
  end

  scope :cartitems_product, -> do
    select("cart_items.*, sum(count) AS count").
    group("product_id")
  end

  scope :cartorder, -> do
    select("cart_items.*, sum(count) AS count").
    group_by(&:group_by_criteria)
  end

  def group_by_criteria
    created_at.to_date.to_s(:db)
  end

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  default_scope -> {order(created_at: :desc)}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_many :comments, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :product_vieweds, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  mount_uploader :upPicture, PictureUploader

  validates :category_id, presence: true
  #validates :productPrice, presence: true, numericality: {only_integer: true}
  default_scope -> {order(created_at: :desc)} 

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      product = find_by_id(row["productname"]) || new
      parameters = ActionController::Parameters.new(row.to_hash)
      product.update(parameters.permit(:productname, :productPrice, :productStatus,:productDescription, :rate, :upPicture, :category_id))
      product.save!  
    
    end
  end

  scope :search_product, ->search do   
    where("productname LIKE ?","%#{search}%").order "productPrice" if search.present?
  end

  scope :hot_product, -> do
  where(productStatus: true).limit(4)
  end
  
 scope :product_create, -> do
  select("products.*,count(id) AS count").
  group_by(&:group_by_criteria)
  end

  def group_by_criteria
    created_at.to_date.to_s(:db)
  end
  
end

app/models/product_viewed.rb
class ProductViewed < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :product

  scope :count_user, ->id do  
  select("rates.*, count(user_id) AS count").
      where("product_id = ?", id)
  end
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :user

  mount_uploader :up_picture, PictureUploader
  scope :suggest_user, ->id do  
  select("suggests.*").
      where("user_id = ?", id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save {email.downcase!}

  has_many :comments, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :suggests, dependent: :destroy
  has_many :product_vieweds, dependent: :destroy
  has_one  :carts, dependent: :destroy
  
  validates :name,  presence: {message: "enter name please"}, length: {maximum: Settings.maximum_name}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: Settings.maximum_email},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: Settings.minimum_password}

  def current_user? user
    self == user
  end

  scope :user_date, -> do
  select("users.*,").
    group("updated_at")
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :logged_in_user, only: :show
  before_action :check_admin, only: :show
  before_action :set_products, only: [:index, :show]
  before_action :create_cart, only: :show

  def new
    session[:cart]=session[:cart] ||= Hash.new
    @products = Product.find_by id: params[:product_id]
    @comments = @products.comments
    @rates = Rate.find_by(product_id: @products.id, user_id: current_user.id) unless current_user.nil?
  end

  def create
    id = params[:product_id]
    count = params[:count] 
    @cart = session[:cart]
    @cart[id] = @cart[id] ? (@cart[id].to_i + count.to_i) : count.to_i
    redirect_to action: :index
  end


  def index
    
  end

  def destroy
    session[:cart].delete params[:id]
    redirect_to action: :index
  end

  def show
    @products.each do |product, count|
      @cartitem = CartItem.find_by(product_id: product.id, cart_id: @cart.id)
      if @cartitem
        count +=  @cartitem.count
        @cartitem.update(count: count)
      else
        @addcart = CartItem.create! price: product.
        productPrice, cart_id: @cart.id, product_id: product.id, count: count
      end
    end
    redirect_to orders_path
  end
  
  private
  
  def set_products 
    @cart = session[:cart] ? session[:cart] : Hash.new
    @products = @cart.map {|id, count| [Product.find_by(id: id), count]}
  end

  def create_cart
    if Cart.find_by(user_id: current_user.id).present?
     @cart = Cart.find_by(user_id: current_user.id)
    else
     @cart = Cart.create! user_id: current_user.id
    end
  end

  def logged_in_user
    unless logged_in? 
      store_location
      flash[:danger] = t "check_log_in"
      redirect_to login_url
    end
  end
  def check_admin
    if current_user.is_admin?
      flash[:danger] = t "you_are_admin"
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rates_helper.rb
module RatesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def current_user
      @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to session[:forwarding_url] || default
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/suggests_helper.rb
module SuggestsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/shared/_carts_form.html.erb
<%= form_tag action: "create" do %>  
  <%= hidden_field_tag :product_id, @products.id %>  
  <input id="count" name="count" type="number" min="1" value = 1 class="form-control" />
  <%= submit_tag "add to cart", class: "btn btn-primary"  %> 
<% end %>  

app/views/shared/_comment_form.html.erb
<%= form_tag comments_path, method: :post, remote: true do %>
  <div class="col-md-12">
  	<div class="col-md-8">
      <%= text_area_tag :content, nil, :rows => 3, :cols => 7, id: "comment_content" %>
      <%= hidden_field_tag :id, @products.id %> 
    </div>
    <div class="col-md-4">
   </div>
   </div>
   <div class="col-md-12">
  	<div class="col-md-2">
    	<%= submit_tag "comment", class: "btn btn-info" %>
    </div>
    <div class="col-md-10">
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-danger">
      <%= t "error_msg" %>
      <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_form_product.html.erb
<h2><%= t ".add_products_by_form" %></h2>
<%= form_for([:admin, @product], html: { multipart: true }) do |f| %>
  <%= render 'shared/error_messages', object: @product %>
  <div class="field">
    <%= f.text_field :productname, placeholder:  t("enter_name"), 
      class: "form-control" %>
    <%= f.text_field :productPrice, placeholder: t("enter_price"), 
      class: "form-control" %>
    <%= f.select(:productStatus, 
      options_for_select([[t(".hot"), 1], [t("normal"), 0]]), {}, 
      {class: "form-control"}) %>
    <%= f.text_area :productDescription, placeholder: t("description"),
      class: "form-control" %>
    <span class="picture">
    <%= f.hidden_field :category_id, value: @category.id %>
    <%= f.file_field :upPicture %>
    </span>
  </div>
  <%= f.submit t("add"), class: "btn btn-primary" %>
<% end %>

app/views/shared/_form_search.html.erb
<%= form_tag root_path, method: :get do %>
  <div class="col-md-12 sidenav">
  	 <div class="col-md-9 sidenav">
  <%= text_field_tag :search, params[:search], 
    class: "form-control", placeholder: ("search products") %>
</div>
 <div class="col-md-3 sidenav">
  <%= submit_tag  "seach products", :class => "btn btn-default" %>
</div>
</div>
<% end %>

app/views/shared/_import_form.html.erb
<%= form_tag admin_csv_index_path, multipart: true do  %>
  <%= file_field_tag :file %>
  <%= submit_tag t(".import") %>
<% end %>

app/views/shared/_suggest_form.html.erb
<%= form_for @suggest, html: {multipart: true} do |f| %>
  <%= render 'shared/error_messages', object: @suggest %>
  <div class="field">
    <%= f.text_field :name, placeholder:  t("enter_name"), 
      class: "form-control" %>
    <%= f.text_area :content, placeholder: t("description"),
      class: "form-control" %>
    <span class="picture">
    <%= f.file_field :up_picture %>
    </span>
  </div>
  <%= f.submit yield(:text_submit), class: "btn btn-primary" %>
<% end %>