config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  
  get "users/new"
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  get    "/login", to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :categories
    resources :products
    resources :orders
    resources :suggests
    resources :charts
    resources :csv, only: :create
  end
  resources :users
  resources :products, only: [:index, :show]
  resources :carts
  resources :orders
  resources :rates
  resources :suggests  
  resources :comments
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :load_category, only: [:show, :destroy]

  def index
    @categories = Category.paginate page: params[:page], per_page: Settings.category_per_page
  end

  def new
    @category = Category.new
  end

  def show
    if @category.blank?
      @products = Settings.blank
    else
      @products = @category.products
        .paginate page: params[:page], per_page: Settings.category_per_page
    end
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to admin_categories_url
    else
      flash[:danger] = t "create_category_fail"
      render :index
    end
  end

  def destroy
    if @category.products.any?
      flash[:danger] = t "fail_delete_category"
    else
      @category.destroy
      flash[:success] = t "category_deleted"
    end
    redirect_to admin_categories_url
  end

  private

  def category_params
    params.require(:category).permit :name, :decription
  end

  def load_category
    @category = Category.find_by id: params[:id]
  end

end

app/views/admin/categories/index.html.erb
<% provide :title, t(".all_Category") %>
<h1><%= t ".all_Category" %></h1>
<table class="table table-inverse">
  <% @categories.each do |category| %>
    <tbody>
      <tr>
        <th><%= link_to category.name, admin_category_path(category) %></th>
        <th><%= category.decription %></th>
        <th><%= t ".id_category" %> <%= category.id %></th>
        <th><%= link_to t(".delete"), admin_category_path(category), 
          method: :delete,data: { confirm: t("confirm_delete") }, 
          class: "btn btn-danger custom"  %></th>
      </tr>
    <tbody>
  <% end %>
</table>
<%= will_paginate @categories %>
<%= link_to t(".add_category"), new_admin_category_path, 
  class: "btn btn-success customadd" %>
<%= link_to t(".add_products_csv"), new_admin_product_path, class: "btn btn-success customadd" %>

app/views/admin/categories/new.html.erb
<% provide :title, t(".add_category") %>
<h1><%= t ".add_category" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
   <%= form_for @category, url: admin_categories_path do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.label :decription %>
      <%= f.text_area :decription, class: 'form-control' %>
      <%= f.submit t(".add"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/show.html.erb
<% provide :title, @category.name %>
<div class="row">
  <aside class="col-md-2">
    <section class="user_info">
      <h1>
        <%= @category.name %>
      </h1>
    </section>
  </aside>
<div class="col-md-10">
  <% if @category.products.any? %>
    <h3><%= t ".products" %>(<%= @category.products.count %>)</h3>
    <ol class="categorys">
    <table class="table table-striped">
       <%= render @products %>
    </table>
    </ol>
    <%= will_paginate @products %>
  <% end %>
  <%= link_to t(".add"), new_admin_product_path(cate_id: @category.id), class: "btn btn-success custom"%>
  </div>
</div>