config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  
  get "users/new"
  root "static_pages#home"
  get  "/signup",  to: "users#new"
  post "/signup",  to: "users#create"
  get    "/login", to: "sessions#new"
  post   "/login",  to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    resources :categories
    resources :products
    resources :orders
    resources :suggests
    resources :charts
    resources :csv, only: :create
  end
  resources :users
  resources :products, only: [:index, :show]
  resources :carts
  resources :orders
  resources :rates
  resources :suggests  
  resources :comments
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category

  has_many :comments, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :product_vieweds, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  mount_uploader :upPicture, PictureUploader

  validates :category_id, presence: true
  #validates :productPrice, presence: true, numericality: {only_integer: true}
  default_scope -> {order(created_at: :desc)} 

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      product = find_by_id(row["productname"]) || new
      parameters = ActionController::Parameters.new(row.to_hash)
      product.update(parameters.permit(:productname, :productPrice, :productStatus,:productDescription, :rate, :upPicture, :category_id))
      product.save!  
    
    end
  end

  scope :search_product, ->search do   
    where("productname LIKE ?","%#{search}%").order "productPrice" if search.present?
  end

  scope :hot_product, -> do
  where(productStatus: true).limit(4)
  end
  
 scope :product_create, -> do
  select("products.*,count(id) AS count").
  group_by(&:group_by_criteria)
  end

  def group_by_criteria
    created_at.to_date.to_s(:db)
  end
  
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController

  before_action :load_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.search_product(params[:search])
      .paginate page: params[:page], per_page: Settings.per_page 
  end

  def new
    @category = Category.find_by id: params[:cate_id]
    @product = Product.new
  end

  def edit 
  end

  def update 
    if @product.update_attributes product_params
       flash[:success] = t ".update_success"
       redirect_to admin_categories_path
    else
       flash[:notice] = t".update_fail"
       render :edit
    end
  end

  def show
  end

  def create
    @product = Product.new product_params
    respond_to do |format|
      if @product.save
        format.html {redirect_to admin_category_url params[:product][:category_id], 
          notice: t(".product_successfully_created")}
      else
        format.html {render :new}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @product.destroy
        format.html {redirect_to products_url}
      else
        format.html {redirect_to :back}
      end
      format.js {render layout: false}
    end
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    render file: Settings.page_404_url unless @product
  end

  def product_params
    params.require(:product)
      .permit :name, :price, :is_status, :description, 
        :rate, :up_picture, :category_id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index  
    @products=Product.search_product(params[:search])
      .paginate page: params[:page], per_page: Settings.per_page 
  end

  def show
    @product=Product.find_by id: params[:id]
  end

  private

  def product_params
    params.require(:product).permit :productname, :productPrice, :productStatus,:productDescription, :rate, :upPicture, :category_id
  end
end

app/views/admin/products/_product.html.erb
<tr>
  <th><span class="content"><%= product.id %></span></th>
  <th><span class="content"><%= product.productname %></span></th>
  <th><span class="content"><%= product.productDescription %></span></th>
  <th><span class="content"><%= product.productPrice %></span></th>
  <th><%= image_tag product.upPicture.url, :size=>"200x100" %></th>
  <th><%= link_to t(".edit_product"),  edit_admin_product_path(product), 
    class: "btn btn-primary" %></th>
  <% if logged_in? && current_user.is_admin %>
  <th><%= link_to t(".delete"), admin_product_path(product), method: :delete,
	  data: { confirm: t("confirm_delete") },remote: true, class: "delete_product" %></th>
  <% end %>
</tr>

app/views/admin/products/destroy.js.erb
$('.delete_product').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/admin/products/edit.html.erb
<% provide(:title, t(".edit_product")) %>
<h1><%= t ".edit_product"%></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @product] do |f| %>
       <%= render "shared/error_messages", object: @product %>
         <div class="field">
           <%= f.text_field :productname, placeholder:  t("enter_name"), 
             class: "form-control" %>
           <%= f.text_field :productPrice, placeholder: t("enter_price"), 
             class: "form-control" %>
           <%= f.select(:productStatus, 
             options_for_select([[t(".hot"), 1], [t("normal"), 0]]), {}, 
             {class: "form-control"}) %>
           <%= f.text_area :productDescription, placeholder: t("description"),
              class: "form-control"  %>
           <span class="picture">
             <%= f.file_field :upPicture %>
           </span>
         </div>
      <%= f.submit ("Edit"), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<h1><%= t ".all_Products" %></h1>
  <table>
    <tr>
      <th>
        <%= form_tag admin_products_path, method: :get do %>
          <%= text_field_tag :search, params[:search], 
            class: "form-control", placeholder: ("search products") %>
          <%= submit_tag  "seach products", :class => "btn btn-info" %>
        <% end %>
      </th>
    </tr>
  </table>
  <table class = "table">
    <tr>
      <th><%= render @products %></th>
    </tr>
  </table>
  <%= will_paginate @products %>

app/views/admin/products/new.html.erb
<% if @category.present? %>
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <%= render "shared/form_product", locals: {product: @product} %>
      
  </div>
  <div class="col-md-2">
  </div>
</div>
<% else %>
<div class="row">
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
    <h2><%= t ".add_products_from_csv" %></h2>
     <%= render "shared/import_form"%>		
  </div>
  <div class="col-md-2">
  </div>
</div>
<% end %>

app/views/admin/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="carousel slide" data-ride="carousel">
         <th><%= image_tag @product.upPicture.url if @product.upPicture? %></th>
      </div>
    </div>
    <div class="col-sm-9">
      <div class="well">
        <p><%= @product.productname %></p>
      </div>
      <div class="well">
        <p><%= @product.productDescription %></p><hr>
        <p><%= @product.productPrice %></p><hr>
        <p><%= time_ago_in_words(@product.created_at) %></p>
      </div>
      <div class="well">
        <p><%= link_to t(".add_to_shopping_cart"), 
          new_cart_path(product_id: @product.id) %></p>
      </div>
    </div>
  </div>
</div>